#ifndef DB_DEFINES_H
#define DB_DEFINES_H

#include <QList>
#include <QString>

// TODO: Query these from the database instead of hard-coding them.

static const QList<QString> db_base_params ({   "description",
                                                "footprint_ref",
                                                "footprint_path",
                                                "library_ref",
                                                "library_path"});


static const QList<QString> db_mfg_params({ "mfg_1",
                               "mfg_1_part_number",
                               "mfg_1_preferred",
                               "mfg_1_date_added",
                               "mfg_1_added_by",
                               "mfg_1_date_inactivated",
                               "mfg_1_inactivated_by",
                               "mfg_1_notes",
                               "mfg_1_datasheet",
                               "mfg_1_rohs_status",
                               "mfg_1_rohs_sheet",
                               "mfg_1_ce_sheet",
                               "mfg_1_ul_sheet",
                               "mfg_2",
                               "mfg_2_part_number",
                               "mfg_2_preferred",
                               "mfg_2_date_added",
                               "mfg_2_added_by",
                               "mfg_2_date_inactivated",
                               "mfg_2_inactivated_by",
                               "mfg_2_notes",
                               "mfg_2_datasheet",
                               "mfg_2_rohs_status",
                               "mfg_2_rohs_sheet",
                               "mfg_2_ce_sheet",
                               "mfg_2_ul_sheet",
                               "mfg_3",
                               "mfg_3_part_number",
                               "mfg_3_preferred",
                               "mfg_3_date_added",
                               "mfg_3_added_by",
                               "mfg_3_date_inactivated",
                               "mfg_3_inactivated_by",
                               "mfg_3_notes",
                               "mfg_3_datasheet",
                               "mfg_3_rohs_status",
                               "mfg_3_rohs_sheet",
                               "mfg_3_ce_sheet",
                               "mfg_3_ul_sheet",
                               "mfg_4",
                               "mfg_4_part_number",
                               "mfg_4_preferred",
                               "mfg_4_date_added",
                               "mfg_4_added_by",
                               "mfg_4_date_inactivated",
                               "mfg_4_inactivated_by",
                               "mfg_4_notes",
                               "mfg_4_datasheet",
                               "mfg_4_rohs_status",
                               "mfg_4_rohs_sheet",
                               "mfg_4_ce_sheet",
                               "mfg_4_ul_sheet",
                               "mfg_5",
                               "mfg_5_part_number",
                               "mfg_5_preferred",
                               "mfg_5_date_added",
                               "mfg_5_added_by",
                               "mfg_5_date_inactivated",
                               "mfg_5_inactivated_by",
                               "mfg_5_notes",
                               "mfg_5_datasheet",
                               "mfg_5_rohs_status",
                               "mfg_5_rohs_sheet",
                               "mfg_5_ce_sheet",
                               "mfg_5_ul_sheet",
                               "mfg_6",
                               "mfg_6_part_number",
                               "mfg_6_preferred",
                               "mfg_6_date_added",
                               "mfg_6_added_by",
                               "mfg_6_date_inactivated",
                               "mfg_6_inactivated_by",
                               "mfg_6_notes",
                               "mfg_6_datasheet",
                               "mfg_6_rohs_status",
                               "mfg_6_rohs_sheet",
                               "mfg_6_ce_sheet",
                               "mfg_6_ul_sheet",
                               "mfg_7",
                               "mfg_7_part_number",
                               "mfg_7_preferred",
                               "mfg_7_date_added",
                               "mfg_7_added_by",
                               "mfg_7_date_inactivated",
                               "mfg_7_inactivated_by",
                               "mfg_7_notes",
                               "mfg_7_datasheet",
                               "mfg_7_rohs_status",
                               "mfg_7_rohs_sheet",
                               "mfg_7_ce_sheet",
                               "mfg_7_ul_sheet",
                               "mfg_8",
                               "mfg_8_part_number",
                               "mfg_8_preferred",
                               "mfg_8_date_added",
                               "mfg_8_added_by",
                               "mfg_8_date_inactivated",
                               "mfg_8_inactivated_by",
                               "mfg_8_notes",
                               "mfg_8_datasheet",
                               "mfg_8_rohs_status",
                               "mfg_8_rohs_sheet",
                               "mfg_8_ce_sheet",
                               "mfg_8_ul_sheet",
                               "mfg_9",
                               "mfg_9_part_number",
                               "mfg_9_preferred",
                               "mfg_9_date_added",
                               "mfg_9_added_by",
                               "mfg_9_date_inactivated",
                               "mfg_9_inactivated_by",
                               "mfg_9_notes",
                               "mfg_9_datasheet",
                               "mfg_9_rohs_status",
                               "mfg_9_rohs_sheet",
                               "mfg_9_ce_sheet",
                               "mfg_9_ul_sheet",
                               "mfg_10",
                               "mfg_10_part_number",
                               "mfg_10_preferred",
                               "mfg_10_date_added",
                               "mfg_10_added_by",
                               "mfg_10_date_inactivated",
                               "mfg_10_inactivated_by",
                               "mfg_10_notes",
                               "mfg_10_datasheet",
                               "mfg_10_rohs_status",
                               "mfg_10_rohs_sheet",
                               "mfg_10_ce_sheet",
                               "mfg_10_ul_sheet",
                               "mfg_11",
                               "mfg_11_part_number",
                               "mfg_11_preferred",
                               "mfg_11_date_added",
                               "mfg_11_added_by",
                               "mfg_11_date_inactivated",
                               "mfg_11_inactivated_by",
                               "mfg_11_notes",
                               "mfg_11_datasheet",
                               "mfg_11_rohs_status",
                               "mfg_11_rohs_sheet",
                               "mfg_11_ce_sheet",
                               "mfg_11_ul_sheet",
                               "mfg_12",
                               "mfg_12_part_number",
                               "mfg_12_preferred",
                               "mfg_12_date_added",
                               "mfg_12_added_by",
                               "mfg_12_date_inactivated",
                               "mfg_12_inactivated_by",
                               "mfg_12_notes",
                               "mfg_12_datasheet",
                               "mfg_12_rohs_status",
                               "mfg_12_rohs_sheet",
                               "mfg_12_ce_sheet",
                               "mfg_12_ul_sheet",
                               "mfg_13",
                               "mfg_13_part_number",
                               "mfg_13_preferred",
                               "mfg_13_date_added",
                               "mfg_13_added_by",
                               "mfg_13_date_inactivated",
                               "mfg_13_inactivated_by",
                               "mfg_13_notes",
                               "mfg_13_datasheet",
                               "mfg_13_rohs_status",
                               "mfg_13_rohs_sheet",
                               "mfg_13_ce_sheet",
                               "mfg_13_ul_sheet",
                               "mfg_14",
                               "mfg_14_part_number",
                               "mfg_14_preferred",
                               "mfg_14_date_added",
                               "mfg_14_added_by",
                               "mfg_14_date_inactivated",
                               "mfg_14_inactivated_by",
                               "mfg_14_notes",
                               "mfg_14_datasheet",
                               "mfg_14_rohs_status",
                               "mfg_14_rohs_sheet",
                               "mfg_14_ce_sheet",
                               "mfg_14_ul_sheet",
                               "mfg_15",
                               "mfg_15_part_number",
                               "mfg_15_preferred",
                               "mfg_15_date_added",
                               "mfg_15_added_by",
                               "mfg_15_date_inactivated",
                               "mfg_15_inactivated_by",
                               "mfg_15_notes",
                               "mfg_15_datasheet",
                               "mfg_15_rohs_status",
                               "mfg_15_rohs_sheet",
                               "mfg_15_ce_sheet",
                               "mfg_15_ul_sheet"});


static const QList<QString> db_capacitor_params ({   "capacitance",
                                        "tolerance",
                                        "voltage",
                                        "temperature_coefficient"});


static const QList<QString> db_connector_params ({   "number_of_positions",
                                        "number_of_rows",
                                        "contact_finish",
                                        "current",
                                        "voltage",
                                        "wire_gauge"});


static const QList<QString> db_diode_params ({       "type",
                                        "current_reverse",
                                        "voltage_forward",
                                        "voltage_zener",
                                        "tolerance",
                                        "power_max",
                                        "impedance_max",
                                        "capacitance",
                                        "reverse_recovery_time"});


static const QList<QString> db_electromechanical_params ({   "type",
                                                "current_rating",
                                                "voltage_rating",
                                                "on_state_resistance",
                                                "voltage_input",
                                                "voltage_load",
                                                "circuit",
                                                "coil_type",
                                                "coil_current",
                                                "coil_voltage",
                                                "voltage_on",
                                                "voltage_off",
                                                "operating_time",
                                                "release_time"});


static const QList<QString> db_filter_params ({  "filter_type",
                                    "impedance",
                                    "inductance",
                                    "bandwidth",
                                    "frequency",
                                    "resistance",
                                    "voltage_rating",
                                    "current_rating",
                                    "operating_temperature"});


static const QList<QString> db_fuse_params ({    "fuse_type",
                                    "current_rating",
                                    "response_time",
                                    "voltage_rating_ac",
                                    "voltage_rating_dc",
                                    "breaking_capacity"});


static const QList<QString> db_ic_params ({"operating_temperature"});


static const QList<QString> db_inductor_params ({"inductance",
                                    "tolerance",
                                    "core_material",
                                    "current_rating",
                                    "resistance",
                                    "operating_temperature"});


static const QList<QString> db_mechanical_params ({"mechanical_type"});


static const QList<QString> db_optoelectronic_params ({  "color",
                                            "wavelength",
                                            "power_dissipation",
                                            "voltage_forward",
                                            "current_rating",
                                            "millicandela_rating"});


static const QList<QString> db_oscillator_params ({  "frequency",
                                        "tolerance",
                                        "load_capacitance",
                                        "equivalent_series_resistance",
                                        "voltage",
                                        "current",
                                        "output_type"});


static const QList<QString> db_power_params ({   "type",
                                    "voltage_input_min",
                                    "voltage_input_max",
                                    "voltage_output_1",
                                    "voltage_output_2",
                                    "voltage_output_3",
                                    "number_of_outputs",
                                    "current_output",
                                    "voltage_isolation",
                                    "power",
                                    "efficiency"});


static const QList<QString> db_resistor_params ({"resistance",
                                    "tolerance",
                                    "power",
                                    "operating_temperature",
                                    "temperature_coefficient"});


static const QList<QString> db_transformer_params ({ "transformer_type",
                                        "voltage_primary",
                                        "voltage_secondary",
                                        "center_tap",
                                        "power_max",
                                        "current_output",
                                        "voltage_isolation",
                                        "inductance",
                                        "turns_ratio"});


static const QList<QString> db_transistor_params ({  "transistor_type",
                                        "power_max",
                                        "operating_temperature",
                                        "current_collector",
                                        "vce_breakdown",
                                        "vce_saturation",
                                        "dc_current_gain",
                                        "current_drain",
                                        "vdss",
                                        "drive_voltage",
                                        "vgs",
                                        "rds_on"});

static const std::map<QString, QList<QString>> table_params_map {{ QString("Capacitor"), db_capacitor_params },
                                                                 { QString("Connector"), db_connector_params },
                                                                 { QString("Diode"), db_diode_params },
                                                                 { QString("Electromechanical"), db_electromechanical_params },
                                                                 { QString("Filter"), db_filter_params },
                                                                 { QString("Fuse"), db_fuse_params },
                                                                 { QString("IC"), db_ic_params },
                                                                 { QString("Inductor"), db_inductor_params },
                                                                 { QString("Mechanical"), db_mechanical_params },
                                                                 { QString("Optoelectronic"), db_optoelectronic_params },
                                                                 { QString("Oscillator"), db_oscillator_params },
                                                                 { QString("Power"), db_power_params },
                                                                 { QString("Resistor"), db_resistor_params },
                                                                 { QString("Transformer"), db_transformer_params },
                                                                 { QString("Transistor"), db_transistor_params }};
#endif // DB_DEFINES_H
